### ISSUE TITLE
Issues for September 26

### ISSUE THREAD

**Issue by toekneesunshine** [NeuroDataDesign/seelviz-f16s17#14]
Required Deliverables:

Tony
- [x] Clustering -- learn about clustering.  Make a LaTeX (or Markdown) file explaining what K-means, K-medeods, Spectral, Louvain do.  Explain basics of implementation, and include a pro/con table discussing what each does well/poorly with examples for each. Include basic algorithms.
- [x] Write pseudocode for clustering graphs [see Ryan's Git Issue on LaTeX]

Link: https://neurodatadesign.github.io/seelviz/Jupyter/ClusteringTechniques.html

Reach Goals:
- [x] Jupyter notebook with Clustering on our data
  - As per Jovo's recommendation from office hours, I first ran clustering on known datasets so I knew that implementation-wise it made sense.  As i discussed during the presentation, I ran through the handwriting images tutorial from SciKit.  I then implemented K-means for K = 2 (Greg's suggestion from TA hours) and then a few additional K's.  Results can be seen [here](https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/reveal/week_926.ipynb), on our main presentation page.  The code implementation is [here](https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/Example%20Clustering%20on%20Fear199.ipynb).

Jon
- [x] Turn API into pipeline form: Running should output wanted graphs

Link: https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/ClarityViz%20Pipeline.ipynb

Reach Goals:
- [ ] Learn about what Leo's code/algorithms for GraphX does.  Make a LaTeX (or Markdown) file explaining the code.
- [ ] Crosscheck all parts to make sure it is accurate

Albert 
- [x] Kwame pipeline tutorials - deliverable is jupyter notebook running his tutorial
  https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Kwame%20Registration%20Notebook%201.ipynb
  https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Kwame%20Registration%20Notebook%202.ipynb
- [x] Get the atlas aligned data from Kwame
  https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/croppedbrain.jpg
- [x] Acquire new data and see if we still have problems with it
  https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/newBrain.png
  -> PROBLEMS: We still have problems, largely we need the new data to be propagated in order for us to play around with it. We have Kwame's images however one of the images seem to be "damaged" -> https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/novisionbrain.png and
  https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/damagedbrain.png
- [x] Using the atlas aligned images, play around with atlas coordinates
  https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/Manual%20Extraction%20of%20RGB-%3EHSv%20Clarity.ipynb

Reach Goals:
- [ ] Run Kwame Pipeline on new data
  -> Incomplete the other file was no propagated thus I was unable to run it through Kwame's pipeline
  https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/AileyRegistration.ipynb

Luke
- [x] Go back and make weighted versions of our graphs (decide on a weight function [e^(-distance), for instance])
- [x] Make graphs similar to Greg's

Reach Goals:
- [ ] Write up analysis of results

Daniel
- [x] Read https://arxiv.org/abs/1312.4318 http://www.nature.com/nmeth/journal/v10/n6/full/nmeth.2481.html http://www.sciencedirect.com/science/article/pii/0165027081900455
- [x] Look through Jon's scripts and understand all the functions

**Comment by toekneesunshine** [comment]
@gkiar

**Comment by mlee156** [comment]
@jovo

**Comment by jovo** [comment]
i don't understand, who is doing what?

**Comment by mlee156** [comment]
@jovo I edited the issues, are there any additional recommendations you have?

**Comment by gkiar** [comment]
Be more specific about @jonl1096 s goal, please. You mean graph explorer? Leo writes lots of cool code :)
