### ISSUE TITLE
November 7th Deliverables

### ISSUE THREAD

**Issue by mlee156** [NeuroDataDesign/seelviz-f16s17#27]
@alee156 and @lukezhu1 
- [x] Provide clearer explanation on how to use our web service
Need to make clearer however http://128.220.11.5:8100/clarityviz/ has explanations
- [x] Fix epsilon ball size so that density plot plotlys are visible (not black)
Showed Ailey visible plotly's (Jovo can verify) links don't work anymore because we're over the limit. A deliverable next week will be to clean out our github repository.
- [x] Find out exactly how much time it takes to run Ailey's brain on server
Exactly 41.2 minutes on Cortex
-------------------------------------------------------------------------------------------
- [x] Use contours in OpenCV to explore Ailey brain data
https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/objectdetection/Aut1367_contour_analysis.ipynb
- [x] Preliminary Jupyter notebook looking at object detection
https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/objectdetection/Object%20Detection%20with%20Contours%20and%20Filtering.ipynb

@jonl1096 
- [x] Include explanations of each plotly on the html page
- [x] Organize formatting of html page (spacing)
- [x] Load each plotly on separate page
- http://128.220.11.5:8100/clarityviz
-------------------------------------------------------------------------------------------
- [ ] Make ndviz projects showing the Aut brain with overlays of the atlas in both native and ARA orientation
- **Need an account to be made for seelviz**

@toekneesunshine 
- [x] Ilastik analysis on Ailey's brain by Thursday
    - During the Ailey meeting, we discussed how we're going to be getting some sample annotated data from her to serve as the ground truth.
    - I downloaded from ndio level 0 data for Aut1367, and visualized the data in ndviz.  I scheduled a meeting to talk it over with Greg on Friday, November 4.  We decided that for the level 0/1/2 data, it's exceptionally hard to distinguish the difference between individual cells - it would be effectively selecting the bright points.  It makes more sense to just wait for Ailey's labeled data (an image of the raw data can be seen here:  https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Tony/ipynb/Aut1367%20Ilastic%20Exploratory%20Analysis.ipynb
- [x] Host and set up our EC2 instance
    - Jon set our stuff up on Cortex here: http://128.220.11.5:8100/clarityviz/
- [?] Ingest histogram equalized niftis to ndstore (not due Thursday)
    - https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/ndstoreIngestHistEq.ipynb
    - Ran into trouble using imgUpload function from ndstore.
    - Made an issue on ndstore here detailing the problem: https://github.com/neurodata/ndstore/issues/375
-------------------------------------------------------------------------------------------
- [x] For the atlas density plotly, change all the labels to regions
    - Found the data/created a table of ARA atlas ID index --> region mapping (version 3 stored here: https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/ccrf/ccrfCSV.csv)
    - Turns out the version 3 CSV only has the changes from version 2 onwards... thus I went to the original paper and got their data... 
    - Plotly here:  https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/Aut1367_region_color.html
    - Jupyter notebook with process here:  https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/Atlas%20Region%20Graph%20on%20Aut1367.ipynb
- [x] Count number of bright spots in each region by Allen atlas label and create a csv
    - Jupyter notebook with process here (scroll down to middle):  https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/Atlas%20Region%20Graph%20on%20Aut1367.ipynb
    - CSV output here: https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/Aut1367Counts.csv

**Comment by mlee156** [comment]
@jovo @gkiar

**Comment by gkiar** [comment]
👌

**Comment by rmarren1** [comment]
@toekneesunshine I ran into similar issues with global variables in ipython, I fixed it by hard-setting the working directory to where it should be with os.chdir

**Comment by jovo** [comment]
- [ ] what is region 1?
- [ ] < 1-2 task per person this week, don't write who is doing what.
- [ ] webpage - only 1 image per page should make it much less burly
- [ ] link to something that explains the different orientations
- [ ] why are drawing contours?
- [ ] there are plenty of boundaries, you looked in a blank region

**Comment by mnatenz1** [comment]
@jonl1096
The graphical explanation screen on clarityviz takes a really long time to load, and if I scroll down before it fully loads the page gets glitchy. You could try a pop-up loading screen with a progress bar that keeps the user from scrolling until the whole page loads. Maybe one simple graphical explanation in the pop-up.

**Comment by ebridge2** [comment]
@alee156 when going through a lot of your deliverables, I find it somewhat cumbersome to go through the long patches of open output, and it slightly detracts from the readability/presentability of the ipynbs. I think it might make sense if there is a reason to include raw terminal outputs (ie, the numpy arrays in this case) to either limit them down significantly to the point where the only raw output is the actual item you exactly need (ie, a particular statistic/element of a large amount of data that is interesting to compare to another statistic/element of some other string of data), or put together one notebook for visualizations/presentations, and another where you have detailed, raw information if it is actually necessary.
