### ISSUE TITLE
December Goals

### ISSUE THREAD

**Issue by mlee156** [NeuroDataDesign/seelviz-f16s17#33]
- [ ] Make ndviz projects showing all of Ailey's brains (AUT) with overlays of the atlas in both native and ARA orientation
- [ ] Count the number of bright points in each region
- [ ] Make the units in physical space in order to prevent the voxel distortion of the z plane
- [ ] Update registration to Kwame's newest to take ~10 minutes rather than 4 hrs.
- [ ] Obtain a preliminary estimate of connectivity between regions based on the existing brightest points approach
- [ ] Provide detailed instructions for how to best generate manually labeled data for tracing processes

**Comment by mlee156** [comment]
@jovo Should I additionally make all of these issues into separate issues?

**Comment by jovo** [comment]
this is good enough.  i want you guys to have a fuller product backlog, so that each week we are simply choosing elements from their, rather than making up new issues.
