### ISSUE TITLE
Notes for 9/12/16

### ISSUE THREAD

**Issue by toekneesunshine** [NeuroDataDesign/seelviz-f16s17#4]
- [ ] Create product backlog

**Comment by mlee156** [comment]
- [ ] Find representative html and Elii
- [ ] Go to Greg Kiar and use happyplotter (but downsampling we should ask Greg)
- [ ] Compute metrics on graph that Greg knows how to compute, where we compute 8
- [ ] Find out the units for the size of the sphere
- [ ] Find out how hard it would be to overlay Atlas
- [ ] Different ways to overlay, consider the centroid, blocks, boundaries (Elii going to want boundaries, or blocks probably).  Boundaries are the eaisiest
- [ ] Computing graph statistics (compute all 8 of the statistics on the top 100,000)
- [ ] Read myCV glocal look at the basic statistics

**Comment by gkiar** [comment]
- I don't understand the first bullet?
- graph statistics is mentioned twice
- regarding "myCV glocal" jovo meant to look at **his** cv (found at jovo.me), find a paper with 'glocal' in the title, and read it. Make that more clear please

tag me when you've updated it. @toekneesunshine @alee156
