### ISSUE TITLE
November 14th Deliverables

### ISSUE THREAD

**Issue by mlee156** [NeuroDataDesign/seelviz-f16s17#48]
### committed

| task | deliverable |
| :--- | :--- | 
| [**By end of today: Obtain image of the general brain region and report back to Jovo asap**](https://github.com/NeuroDataDesign/seelviz/issues/47) | Messaged Jovo (see [here](https://github.com/NeuroDataDesign/seelviz/issues/47)) |
| [Find the 100,000 bright points for all 3 of Ailey's brains - deliverable is csv files](https://github.com/NeuroDataDesign/seelviz/issues/44) | (https://github.com/NeuroDataDesign/seelviz/issues/44) |
| [Make Website clearer and include instructions for Brain orientation](https://github.com/NeuroDataDesign/seelviz/issues/42) | http://128.220.11.5:8090/ http://128.220.11.5:8100/|
| [Update registration to Kwame's newest registration](https://github.com/NeuroDataDesign/seelviz/issues/38) | https://hub.docker.com/r/lkzhu1/clweb/tags/ |

----

### reach

| task | deliverable |
| :--- | :--- | 
| [Obtain a preliminary estimate of connectivity between regions based on the existing brightest points approach](https://github.com/NeuroDataDesign/seelviz/issues/39) |https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/Aut1367_region_color_connectivity.html https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/preliminary_connectivity_brain_aut1367.ipynb |
| [Ingest 100,00 brightest points and overlay them on both views of the brain](https://github.com/NeuroDataDesign/seelviz/issues/46) |  |
| [Ingest the ARA as a RAMON object so that you can see the names of each region](https://github.com/NeuroDataDesign/seelviz/issues/45) |  |
| [Make ndviz projects showing all of Ailey's brains (AUT) with overlays of the atlas in both native and ARA orientation](https://github.com/NeuroDataDesign/seelviz/issues/35) |  |

**Comment by mlee156** [comment]
@gkiar @jovo

**Comment by jovo** [comment]
this is a big improvement i think.  
i think it would be even better if the deliverable were stated clearly and concisely.
eg, for the 100,000 brightest points, i'll get a csv?

**Comment by rmarren1** [comment]
@jonl1096 It might be easier to see the database links on the website if they were in a table

@alee156 The website doesn't didn't open for me

**Comment by gkiar** [comment]
- proj info
- heirarchical atlas
- alg for graph connectivity

**Comment by tsunwong123** [comment]
@alee156 yeah the website didn't open for any of us. you should probably double check that!

**Comment by ebridge2** [comment]
@alee156 same for me :( other notes, would be interesting to see some details on the connectivity metric you used for making those edges @lukezhu1

**Comment by mlee156** [comment]
I shut down the server after we presented, I just opened it up again
@jonl1096  can you reopen your server as well

**Comment by mnatenz1** [comment]
@alee156 The website's basic content does not adjust correctly to changes in screen dimension (ex. laptop vs. tablet vs. mobile phone).
