### ISSUE TITLE
Deliverables for November 28th

### ISSUE THREAD

**Issue by mlee156** [NeuroDataDesign/seelviz-f16s17#49]
### committed

|status |  deliverable | notes |
| :---|  :--- |  :--- |
|🐉 | [Code.md for connectivity algorithm](https://github.com/NeuroDataDesign/seelviz/issues/39) | @lukezhu1  https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/Connectivity_codemd.ipynb |
| 🍙 | [A registered brain to Allen atlas ingested into ndstore, with ndviz link showing the brain overlaid with the Atlas](https://github.com/NeuroDataDesign/seelviz/issues/53) | http://viz.neurodata.io/Aut1374_albert/# @alee156 @toekneesunshine  |
|🍙 | [Make output webpage have links to everything pertinent](https://github.com/NeuroDataDesign/seelviz/issues/50) | http://cortex.jhu.edu:8900/ @jonl1096 |
----

### reach

|status |  deliverable | notes |
| :---|  :--- |  :--- |
| :x: | [Ingest the ARA as a RAMON object so that you can see the names of each region](https://github.com/NeuroDataDesign/seelviz/issues/45) | @lukezhu1  |
| :x: | [Ingest 100,000 brightest points and overlay them on both views of the brain](https://github.com/NeuroDataDesign/seelviz/issues/46) | @toekneesunshine   |
| :x: | [Figure out how to deal with hierarchical atlas - deliverable is jupyter notebook with our work](https://github.com/NeuroDataDesign/seelviz/issues/51) | @jonl1096 [ipynb](https://github.com/jonl1096/clarityvizwork/blob/master/hierarchy/atlasregion.ipynb)  [html](https://github.com/jonl1096/clarityvizwork/blob/master/hierarchy/output/Aut1367reorient_atlas/Aut1367reorient_atlas_region_pointcloud.html) |
| :x: | [Provide detailed instructions for how to best generate manually labeled data for tracing processes](https://github.com/NeuroDataDesign/seelviz/issues/40) | @lukezhu1  |

**Comment by mlee156** [comment]
@gkiar @jovo 
Just realized that for some reason my tag didn't submit when I made the issue last week ... my bad

**Comment by jovo** [comment]
different histogram equalization code won't solve hierarchy problem.
also, please don't link to this issue, that is not useful for anybody.
otherwise, looks good.

**Comment by jovo** [comment]
@toekneesunshine 
- [ ] have you seen @kkutten1 version of ingesting these? let's talk to him about this.
- [ ] let's get @kkutten1 to be on this team?
- [ ] look at @kkutten1 most recent [notebook](https://github.com/neurodata/ndreg/blob/master/doc/3D_AutA_Registration.ipynb)

@jonl1096 
- [ ] let's look at the actual hierarchy, not the brain, see if you can plot the ARA using whatever for the different levels of the hierarchy

@lukezhu1 
- [ ] do algorithms.md for realz yo.

**Comment by 02agarwalt** [comment]
@jonl1096 for the ipynb, it might be more helpful for viewers if you include some more graphics for the simulations, kind of like in algorithms.md. Right now its mostly consecutive blocks of code which aren't very clear. Some written explanations/overviews would be helpful too.

**Comment by rmarren1** [comment]
the website on cortex links to the website on github pages, then you can't get back. maybe the links need to fixed if that isnt on purpose

**Comment by mnatenz1** [comment]
@lukezhu1 None of the plots you made for the connectivity algorithm.md are working

**Comment by mlee156** [comment]
jupyter notebook rendered plots don't work on github five minutes ago, we are trying to fix it now.

**Comment by kkutten1** [comment]
@toekneesunshine: If you want to talk about image registration let me know
