### ISSUE TITLE
Use different histogram equalization techniques to see if that solves hierarchy problem

### ISSUE THREAD

**Issue by mlee156** [NeuroDataDesign/seelviz-f16s17#52]
Use different histogram equalization techniques to see if that solves hierarchy problem

**Comment by gkiar** [comment]
What do you mean hierarchy problem? Visualization of the hierarchical Atlas? If so, this has nothing to do with your equalization, but just how you are displaying points. Please clarify.

**Comment by mlee156** [comment]
@gkiar I think that the way we're choosing the size of the local points to confer with might have an effect on the "bright points" chosen - if you don't think that'll matter for the hierarchy we can choose a different deliverable!

**Comment by gkiar** [comment]
the hierarchy is by definition a different thing -it's you interpreting the atlas properly. It has nothing to do with the brightest points and for what Ailey wants you don't need to do any brightest point detection currently.
