### ISSUE TITLE
New Deliverables for December 4th Since NDViz is down

### ISSUE THREAD

**Issue by mlee156** [NeuroDataDesign/seelviz-f16s17#57]
Committed

|status |  deliverable | notes |
| :---|  :--- |  :--- |
| 👍   | [Run algorithms.md on connectivity algorithm and check with Jovo - if mutually agreed on update web service to include](https://github.com/NeuroDataDesign/seelviz/issues/45) | @lukezhu1 https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/Connectivity_adjacency_algorithm_md.html https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/pseudocode_new.pdf |
| 👍   | [Update loose ends for the package and web service - more extensive updates since ndviz is down and we need to make up for it.] | @alee156 @lukezhu1 @toekneesunshine @jonl1096 |

Specifically for extensive updates
- [x] Clear instructions for every aspect of web service
http://cortex.jhu.edu:8050/clarityviz/compute/
- [x] Repackaged Docker image for updates
https://hub.docker.com/r/alee156/ailey/

Reach Goals

|status |  deliverable | notes |
| :---|  :--- |  :--- |
| 👍  | [Run baseline atlas without intermediary portions as Jovo directed and report back asap](https://github.com/NeuroDataDesign/seelviz/issues/51) | @toekneesunshine |
| :x: | [Ingest 100,000 brightest points and overlay them on both views of the brain](https://github.com/NeuroDataDesign/seelviz/issues/46) | @toekneesunshine  |
| :x: | [Exploratory analysis jupyter notebook on the ClearMap] (https://github.com/NeuroDataDesign/seelviz/issues/56) | @alee156 |

**Comment by mlee156** [comment]
@jovo

**Comment by jovo** [comment]
ok.  best, however, to not edit this issue, just make comments to explain the pivot decision.

**Comment by jovo** [comment]
- [ ] use code from kwame to determine leaf nodes (i slacked a link to you)
- [ ] where is the csv file / webpage that lists number of bright spots per region
- [ ] fix eigen embedding, show us plot of emebddings into 2D (or run meda on it, our R package)
- [ ] eigen embeddings only basically operate on the largest connected component, so best to discard everything other than that.
- [ ] make the simulation a mixture model, you can make each component spherically symmetric gaussian, and just use different means.  it can be in 2D.
- [ ] have somebody else in the class test your web-service and watch them do it, take notes, and improve their experience
- [ ] put everything in EC2
