### ISSUE TITLE
Product Backlog

### ISSUE THREAD

**Issue by mlee156** [NeuroDataDesign/seelviz-f16s17#6]

**Comment by mlee156** [comment]
false color voxels by component size

Approach: if you choose a size of a ball, then you can color all the points in the
ball based on how many points are in there.
ball size could be very small (the limit to ball size is that points
literally must be adjacent).

**Comment by gkiar** [comment]
Each "product" in the backlog should have a unique issue; not a single issue bloated with lots of unrelated things. close this, and break it out into a new issue? @alee156
