### ISSUE TITLE
Letter of Recommendation for me

### ISSUE THREAD

**Issue by toekneesunshine** [NeuroDataDesign/seelviz-f16s17#62]
Hi @jovo 

As I mentioned in Slack, I finished up a draft of the letter of recommendation (I must say, it feels pretty odd writing about myself in the third person).  I’ve attached a copy on our Slack channel.  I’m free all day Thursday (January 25), and after 12 PM on Friday to go over changes/any details in person!  If you’re not free this week, I can also do the beginning of next week.  The letter has to be submitted by Wednesday, so as long as it’s before then it should be good.

**Comment by jovo** [comment]
@toekneesunshine where do i submit?

**Comment by toekneesunshine** [comment]
@jovo I sent a link to jovo@jhu.edu on January 23 - I'll send another one now!

**Comment by toekneesunshine** [comment]
@jovo - Ah, I just got a confirmation that it's all done!  Thanks again!
