### ISSUE TITLE
Deliverables for Feb 13th

### ISSUE THREAD

**Issue by jonl1096** [NeuroDataDesign/seelviz-f16s17#64]
# Committed

|status |  deliverable | notes |
| :---|  :--- |  :--- |
| 👍 |[paper review about cell counting](https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Albert_Jupyter/Multiple%2BApproaches%2Bfor%2BCell%2BDetection.ipynb) **Note** deliverable changed as noted below by Tony | @alee156 |
| 👍 | https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/Morton%2BCode.html | @lukezhu1  |
| 👍 | connectivity algorithm using region adjacency: [notebook with steps and adjacency matrix](http://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/algorithms/connectivity2.ipynb), [plot of region adjacency](http://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/algorithms/Fear199_region_adjacency.html), [original graph for comparison](http://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/algorithms/Fear199_region.html)| @jonl1096  |
| 👍 | [Methods.md writeup](http://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/Tony/ipynb/Brain%20Cell%20Finder%20Detection%20Methods.ipynb) on  [this paper](https://academic.oup.com/bioinformatics/article/30/17/i587/201138/Large-scale-automated-identification-of-mouse) about cell counting, convince Greg that this is/isn't a good idea. | @toekneesunshine  |

**Comment by toekneesunshine** [comment]
Edited Thursday, at office hours with Greg.  After discussion, my "DoD" is convincing Greg and the team that the paper I found is/or isn't good with some writeup.  The following week I will try to implement it (if it is good).

Paper link [here](https://academic.oup.com/bioinformatics/article/30/17/i587/201138/Large-scale-automated-identification-of-mouse).

Python code and libraries [here](http://bcfind.dinfo.unifi.it/installation.html).

Before:  Methods.md writeup on a paper/method about cell counting
