### ISSUE TITLE
Deliverables for Monday March 27th

### ISSUE THREAD

**Issue by mlee156** [NeuroDataDesign/seelviz-f16s17#69]
@alee156 & @lukezhu1 
- [x] By Thursday: Show Greg both our numpy list of lists, and a sampled area where we generate fibers https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/fibers_plt.ipynb

|status |  deliverable | notes |
| :---|  :--- |  :--- |
| [👍](https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/algorithms/struct_tensor.py) | For Monday during break:  [Show progress of various implementations.](https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/algorithms/struct_tensor.py)  After hearing back from Ailey (about hyper-parameters), talk with Greg about figuring out how to set hyper-parameters in Python/MATLAB code.  | @toekneesunshine @jonl1096  |
| 👍 | For class meeting (Monday, March 27):  Finish implementing new structure tensor code into Python pipeline. [Brain with edges](http://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/algorithms/test.html), [Density graph](http://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/algorithms/Fear199_density.html), [Density Heatmap](http://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/algorithms/Fear199_density_heatmap.html), [Region graph](http://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/algorithms/Fear199_region.html), [Region Centers graph](http://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/algorithms/Fear199_region_adjacency.html), [Working Version of Structure Tensor Script](https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Tony/ipynb/Testing%2BTractography%2BScripts.ipynb), [Old brain plot](http://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/reveal/clarityjs/localeq.html) | @toekneesunshine @jonl1096 |
| :thumbsup: | For Monday during break: [Check dimensions of outputs from Dipy's EuDX example](https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/dipy_example.ipynb) and [fix the bug in visualization that caused the cube-like tiff stack to flatten out](https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/fibers_cube-ish_volume.ipynb) Edit: [Show Greg 100 random fibers from the cube-like volume.](https://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/fibers_cube-ish_volume_100random_fibers.ipynb) | @alee156 @lukezhu1 |
| 👍 | For class meeting (Monday, March 27): Need to determine next steps after meeting with Greg during break. [full brain](https://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/fibers_cube-ish_volume_full_sample_fibers.ipynb) [Example brain comparison](https://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/Jupyter/fibers_cube-ish_volume_hardy_example_comparison.ipynb) [harddi comparison](http://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/Albert_Jupyter/qc/eudx%20%281%29.ipynb) [cross check](http://nbviewer.jupyter.org/github/NeuroDataDesign/seelviz/blob/gh-pages/Albert_Jupyter/qc/hardii_demo.ipynb) | @alee156 @lukezhu1 |

Note: Pivoted because it was very clear evec/eval generation was not working

**Comment by toekneesunshine** [comment]
@gkiar

**Comment by gkiar** [comment]
@alee156 @lukezhu1 to be clear: you're showing me the fibers, and we agreed you would **visualize** some subset of them. If the whole bundle didn't work last time, start with a single fiber and add more up to some saturation point when visualizing on your laptop.
