### ISSUE TITLE
Issue for September 12th

### ISSUE THREAD

**Issue by mlee156** [NeuroDataDesign/seelviz-f16s17#7]
- [x] Send an email to Ailey Crow at aileyc@stanford.edu containing a representative Clarity html plotly file asap
    -> CC'd Jovo to email
- [x] Go to Greg Kiar's github page and use happyplotter
    ->  https://github.com/Upward-Spiral-Science/seelviz/blob/gh-pages/graphfiles/LukeGraphs/Fear199localeq.png?raw=true
  - [x] Ask Greg for help regarding downsampling our data 
    -> Talked to Greg on Friday, we're setting up a meeting after Monday meeting
- [x] Find out the units for the size of the sphere that we used to connect the edges
    -> Very simple answer of voxels
- [x] Find out how hard it would be to overlay an Atlas: Pretty hard
    -> https://github.com/Upward-Spiral-Science/seelviz/blob/gh-pages/pdfs/atlas-fitting-clarity-upload.pdf
- [x] Research different ways to overlay - consider the centroid, blocks, boundaries (Ailey is going to want boundaries, or blocks probably).  Boundaries are the easiest. 
    -> https://github.com/Upward-Spiral-Science/seelviz/blob/gh-pages/pdfs/atlas-fitting-clarity-upload.pdf
  ~~\- [ ] Compute the graph statistics (compute 8 of the statistics on the top 100,000) that you can find on Jovo's glocal look at basic statistics on his CV repository~~
  - [x] Only 7 were calculable because there was not an 8th one in the code 
    -> https://github.com/Upward-Spiral-Science/seelviz/blob/gh-pages/Graph%20Statistics%20For%20Fear199.ipynb

**Comment by mlee156** [comment]
@gkiar Sorry the "issues" that we wrote yesterday were really notes that I made during class, I've created a new set of issues that better represents the deliverables for the week.

**Comment by gkiar** [comment]
👌

**Comment by gkiar** [comment]
Notice my comments on the "backlog" issue? & close the notes one if it is just a duplicate of this.

**Comment by gkiar** [comment]
good work!
